version: '3'
services:
  api:
    container_name: laravel-api
    build:
      context: ./infra/docker
      dockerfile: Dockerfile
    privileged: true
    ports:
      - '80:80'
    volumes:
      - ./api:/var/www/app
    networks:
      - mysql-compose-network
  db:
    container_name: mysql-api
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    env_file:
      - ./infra/mysql/config-db.ini
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network: