version: '3'
services:
  api:
    container_name: laravel-api
    build:
      context: ./infra/docker
      dockerfile: Dockerfile
    privileged: true
    ports:
      - '80:80'
    volumes:
      - ./api:/var/www/app
    networks:
      mysql-compose-network:
        ipv4_address: 172.21.0.3
  db:
    container_name: mysql-api
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    env_file:
      - ./infra/mysql/config-db.ini
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      mysql-compose-network:
        ipv4_address: 172.21.0.9

networks:
  mysql-compose-network:
    ipam:
      driver: default
      config:
        - subnet: '172.21.0.4/24'
